trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  displayName: 'Build Stage'

  jobs:
  - job: Build
    displayName: 'Build Static Website'

    steps:
    - checkout: self

    - script: |
        echo "Starting build..."
        echo "Checking website files..."
        ls -la
      displayName: 'Build Static Website'


- stage: Deploy
  displayName: 'Deploy Stage'

  dependsOn: Build
  condition: succeeded()

  jobs:
  - job: Deploy
    displayName: 'Deploy to Azure Static Web App'

    steps:
    - checkout: self

    - task: AzureStaticWebApp@0
      displayName: 'Deploy to Azure Static Web App'
      inputs:
        app_location: '/'
        output_location: ''
        skip_app_build: true
        skip_api_build: true
        azure_static_web_apps_api_token: $(514c0e5cb9e2f34d89406bf45b791c174562c015148f078fc651aa5a6a95814f02-592f98da-ac63-447b-b4ea-ef1e348674e30101928013b35510)
